# Generated by Django 5.0 on 2023-12-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Regular_Pizza',
        ),
    ]
