# Generated by Django 5.0 on 2023-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_rename_pizza_regular_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_toppins', models.CharField(choices=[('Pizza sencilla', 'Pizza sencilla'), ('Pizza con cobertura', 'Pizza con cobertura'), ('Pizza con doble cobertura', 'Pizza con doble cobertura'), ('Pizza con triple cobertura', 'Pizza con triple cobertura'), ('Pizza especial', 'Pizza especial')], max_length=40)),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Siliciana', 'Siliciana')], max_length=40)),
                ('pizza_size', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Grande', 'Grande')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Regular_Pizza',
        ),
    ]
