# Generated by Django 5.0 on 2023-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizza_delete_regular_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Grande', 'Grande')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Grande', 'Grande')], max_length=40),
        ),
    ]
