# Generated by Django 5.0 on 2023-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_sub_extras_remove_topping_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='description',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
    ]
