# Generated by Django 5.0 on 2023-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_sub_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendiente', max_length=50)),
            ],
        ),
    ]
